// 全局
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SHOW_ACTION_WINDOW = 'SHOW_ACTION_WINDOW';
export const CLOSE_ACTION_WINDOW = 'CLOSE_ACTION_WINDOW';
export const CHANGE_SPIN = 'CHANGE_SPIN';


// 登录
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';

// 餐桌
export const RECEIVE_TABLE_LIST = 'RECEIVE_TABLE_LIST';
export const RECEIVE_PEOPLE_INFO = 'RECEIVE_PEOPLE_INFO';
export const CHANGE_TABLE_CHECKED_STATE = 'CHANGE_TABLE_CHECKED_STATE';
export const CHANGE_PEOPLE_NUM = 'CHANGE_PEOPLE_NUM';
